### ISSUE TITLE
请问数据有公开吗？在哪里下？

### ISSUE THREAD

**Issue by Kregion** [Mingyue-Cheng/TimeMAE#1]

**Comment by Breathtaking1** [comment]
请问代码是不是有问题啊，有些东西是不是少了啊

**Comment by Mingyue-Cheng** [comment]
Thank you for your interest. The data in the Google Drive link below is readily accessible. Should you have any additional questions, please do not hesitate to reach out via email at [mycheng@ustc.edu.cn].

https://drive.google.com/drive/folders/128bIAabc5G3RzyYTonPZv8RWttuQ7Roh?usp=drive_link
